DROP TABLE IF EXISTS User;
CREATE TABLE User (
	id		INT UNSIGNED NOT NULL AUTO_INCREMENT,
	name		TINYTEXT NOT NULL,
	email		TINYTEXT NOT NULL,
	password	TINYTEXT NOT NULL,
	creationDate	DATETIME NOT NULL,
	modifDate	TIMESTAMP NOT NULL,
	PRIMARY KEY (id),
	UNIQUE INDEX email (email(40)),
	INDEX password (password(10)),
	INDEX creationDate (creationDate),
	INDEX modifDate (modifDate)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS Page;
CREATE TABLE Page (
	id		INT UNSIGNED NOT NULL AUTO_INCREMENT,
	title		TINYTEXT NOT NULL,
	skriv		TEXT,
	html		TEXT,
	creationDate	DATETIME NOT NULL,
	modifDate	TIMESTAMP NOT NULL,
	creatorId	INT UNSIGNED NOT NULL DEFAULT '0',
	modifierId	INT UNSIGNED NOT NULL DEFAULT '0',
	priority	TINYINT UNSIGNED NOT NULL DEFAULT '0',
	parentPageId	INT UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (id),
	INDEX parentPageId (parentPageId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

